services:
  scarches:
    build: .
    ports:
      - 8080:8080
    environment:
      - AWS_BUCKET=minio-bucket
      - AWS_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY=minioadmin
      - AWS_SECRET_KEY=minioadmin
    depends_on:
      - minio

  database:
    image: mongo
    ports:
      - 27017:27017

  minio:
    build:
      context: .
      dockerfile: minio.Dockerfile
    ports:
      - 0.0.0.0:9000:9000
      - 0.0.0.0:9001:9001

  minioconfigure:
    build:
      context: .
      dockerfile: minioconfig.Dockerfile
    depends_on:
      - minio

