services:
  database:
    image: mongo
    ports:
      - 27017:27017
  
  redis:
    image: redis

  server:
    build: .
    depends_on:
      - database
      - redis
    ports:
      - 8050:8050
    env_file:
      - .env  
    environment:
      DATABASE_URI: 'mongodb://database:27017/dev'
